#!/bin/python3
from guizero import TextBox,PushButton,App,Text,Combo

app=App(layout="grid",height=100,width=300)
app.title="PyEncrypter"
alphabet = 'abcdefghijklmnopqrstuvwxyz'
keys=[]
def Encrypt():
 i=0
 newMessage = ''
 message=text1.value
 for character in message:
  i=i+1
  i=i % length
  if character in alphabet:
   position = alphabet.find(character)
   newPosition = (position + keys[i]) % 26
   newCharacter = alphabet[newPosition]
   newMessage += newCharacter
  else:
   newMessage += character
 ans.value=newMessage
def Decrypt():
 i=0
 newMessage = ''
 message=text1.value
 for character in message:
  i=i+1
  i=i % length
  if character in alphabet:
   position = alphabet.find(character)
   newPosition = (position - keys[i]) % 26
   newCharacter = alphabet[newPosition]
   newMessage += newCharacter
  else:
   newMessage += character
 ans.value=newMessage
def button():
 global length
 keys.clear()
 k=key.value
 if(k == ''):
  k='0'
  app.error('Error','Please enter a Key')
 length=len(k)
 length=int(length)
 for ch in k:
  ch=int(ch)
  keys.append(ch)
  print(keys)
 if(choice.value == 'Encrypt'):
  Encrypt()
 elif(choice.value == 'Decrypt'):
  Decrypt()
text1=TextBox(master=app,grid=[1,1])
choice=Combo(master=app,options=['Encrypt','Decrypt'],grid=[0,1])
button =PushButton(text='Click',command=button,master=app,grid=[1,3])
info = Text(app,text='Enter the key',grid=[2,1])
key=TextBox(master=app,grid=[2,2])
ans=TextBox(master=app,grid=[1,2])
app.display()
